name: 'ci'

on:
    pull_request:
        types: [labeled, opened, synchronize, unlabeled]
    push:
        branches: [master]
        
jobs:
   setup:
      runs-on: ubuntu-latest
      steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false
            - name: Say Hello world
              run: echo "Hello World"
